# Generated by Django 5.1.4 on 2025-01-29 23:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HabitsBackend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counter',
            old_name='title',
            new_name='counterTitle',
        ),
        migrations.RemoveField(
            model_name='counter',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='counter',
            name='createdOn',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='counter',
            name='updatedAt',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='counter',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
